###
POST https://jobed-connect-api.jobtechdev.se/v1/occupations/match-by-text 
Content-Type: application/json

{
"input_text": "html javascript css", "limit": 10, "offset": 0, "include_metadata": false
}

### 
GET https://jobed-connect-api.jobtechdev.se/v1/enriched_occupations 
Content-Type: application/json

{
"occupation_id": "GDHs_eoz_uKx", "include_metadata": true
}







// EXTRA
###
//SÖKA FRAM ALLA UTBILDNINGAR
GET https://jobed-connect-api.jobtechdev.se/v1/educations?distance=false&filter_education_plan_exists=false
Content-Type: application/json

###
//skicka med query/sökord
GET https://jobed-connect-api.jobtechdev.se/v1/educations?distance=false&filter_education_plan_exists=false
Content-Type: application/json

{
  "query": "frontend", "limit": 100
}

//HÄMTA DATA GÄLLANDE YRKEN
###
//JOBTECHyrkesprognoser- current
GET https://data.jobtechdev.se/yrkesprognoser/current/Yrkesprognos.json
Content-Type: application/application/json

###
//SCB Genomsnittlig månadslön, kronor efter yrke, SSYK
POST https://api.scb.se/OV0104/v1/doris/sv/ssd/START/AM/AM0110/AM0110A/LoneSpridSektorYrk4A
Content-Type: application/json

{
  "query": [
    {
      "code": "Yrke2012",
      "selection": {
        "filter": "item",
        "values": [
          "0000"
        ]
      }
    },
{
      "code": "ContentsCode",
      "selection": {
        "filter": "item",
        "values": [
          "000000C5"
        ]
      }
    },
    {
      "code": "Tid",
      "selection": {
        "filter": "item",
        "values": [
          "2016",
          "2017",
          "2018",
          "2019",
          "2020",
          "2021",
          "2022"
        ]
      }
    }
  ],
  "response": {
    "format": "json"
  }
}

###
//SCB hämta SSYK beskrivningar
GET https://api.scb.se/OV0104/v1/doris/sv/ssd/START/AM/AM0208/AM0208Z/SSYKBeskrivning
Content-Type: application/application/json

# {
#   "query": [
#     {
#       "code": "ContentsCode",
#       "selection": {
#         "filter": "item",
#         "values": [
#           "0000020A"
#         ]
#       }
#     }
#   ],
#   "response": {
#     "format": "json"
#   }
# }
###